Fix broken id broker tests
The tests updated httpcore which broke the provisioning api. The
httpcore package does some on demand import which broke because the
import path change due to the package update.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/asgi_correlation_id/middleware.py", line 87, in __call__
    await self.app(scope, receive, handle_outgoing_request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 108, in __call__
  File "/usr/local/lib/python3.9/site-packages/fastapi_utils/timing.py", line 47, in timing_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 84, in call_next
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 70, in coro
    task_group.cancel_scope.cancel()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    app = Starlette(routes=routes)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    else:
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    values, errors, background_tasks, sub_response, _ = solved_result
  File "/usr/local/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 622, in solve_dependencies
  File "/usr/local/lib/python3.9/site-packages/provisioning_plugin/dependencies.py", line 99, in get_school_class_by_id
    await get_kelvin_obj(
  File "/usr/local/lib/python3.9/site-packages/id_broker_common/kelvin.py", line 108, in get_kelvin_obj
    return await resource.get(**get_kwargs)
  File "/usr/local/lib/python3.9/site-packages/ucsschool/kelvin/client/base.py", line 207, in get
    return await self.get_from_url(url)
  File "/usr/local/lib/python3.9/site-packages/ucsschool/kelvin/client/base.py", line 241, in get_from_url
    resp_json: Dict[str, Any] = await self.session.get(url)
  File "/usr/local/lib/python3.9/site-packages/ucsschool/kelvin/client/session.py", line 238, in get
    return await self.request(self.client.get, url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ucsschool/kelvin/client/session.py", line 182, in request
    kwargs["headers"] = await self.json_headers
  File "/usr/local/lib/python3.9/site-packages/async_property/base.py", line 37, in get_value
    return await self._fget(instance)
  File "/usr/local/lib/python3.9/site-packages/id_broker_common/kelvin.py", line 41, in json_headers
    "Authorization": f"Bearer {await self.token}",
  File "/usr/local/lib/python3.9/site-packages/async_property/base.py", line 37, in get_value
    return await self._fget(instance)
  File "/usr/local/lib/python3.9/site-packages/id_broker_common/kelvin.py", line 50, in token
    resp_json = await self.post(
  File "/usr/local/lib/python3.9/site-packages/ucsschool/kelvin/client/session.py", line 247, in post
    return await self.request(self.client.post, url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ucsschool/kelvin/client/session.py", line 185, in request
    response: httpx.Response = await async_request_method(url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1533, in request
    async def stream(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1620, in send
    follow_redirects=follow_redirects,
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    history=history,
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    await hook(response)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response.request = request
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    # up as HTTP/1.1.
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    # up the exception.
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    origin=self._origin,
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    f"Attempted to send request to {request.url.origin} on connection to {self._origin}"
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 111, in _connect
    "port": self._origin.port,
  File "/usr/local/lib/python3.9/site-packages/httpcore/backends/auto.py", line 28, in connect_tcp
  File "/usr/local/lib/python3.9/site-packages/httpcore/backends/auto.py", line 17, in _init_backend
ModuleNotFoundError: No module named 'httpcore.backends.asyncio'
```

Issue univention/ucsschool-components/id-broker-self-disclosure-db-builder#23