Bug #49462: fix univention.testing.ucsschool.importou.parametrization_id_base64_decode()
git:6adbb37bf42f29620678f54634a84af927acac30 introduced univention.testing.ucsschool.importou.parametrization_id_base64_decode() which is used as ids= function for pytest.mark.parametrize.
This function is expected to return a string. the actual function returns anything. This breaks with newer pytest versions.

____________ ERROR collecting 30_import-create_ou_via_python_api.py ____________
/usr/lib/python2.7/dist-packages/pluggy/hooks.py:284: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
/usr/lib/python2.7/dist-packages/pluggy/manager.py:67: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python2.7/dist-packages/pluggy/manager.py:61: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
/usr/lib/python2.7/dist-packages/_pytest/python.py:224: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
/usr/lib/python2.7/dist-packages/_pytest/python.py:409: in _genfunctions
    self.ihook.pytest_generate_tests(metafunc=metafunc)
/usr/lib/python2.7/dist-packages/pluggy/hooks.py:284: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
/usr/lib/python2.7/dist-packages/pluggy/manager.py:67: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python2.7/dist-packages/pluggy/manager.py:61: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
/usr/lib/python2.7/dist-packages/_pytest/python.py:133: in pytest_generate_tests
    metafunc.parametrize(*marker.args, **marker.kwargs)
/usr/lib/python2.7/dist-packages/_pytest/python.py:953: in parametrize
    ids = self._resolve_arg_ids(argnames, ids, parameters, item=self.definition)
/usr/lib/python2.7/dist-packages/_pytest/python.py:1007: in _resolve_arg_ids
    ids = idmaker(argnames, parameters, idfn, ids, self.config, item=item)
/usr/lib/python2.7/dist-packages/_pytest/python.py:1197: in idmaker
    for valindex, parameterset in enumerate(parametersets)
/usr/lib/python2.7/dist-packages/_pytest/python.py:1187: in _idvalset
    for val, argname in zip(parameterset.values, argnames)
/usr/lib/python2.7/dist-packages/_pytest/python.py:1159: in _idval
    return ascii_escaped(s)
/usr/lib/python2.7/dist-packages/_pytest/compat.py:248: in ascii_escaped
    return val.encode("unicode-escape")
E   AttributeError: 'bool' object has no attribute 'encode'