Do not set exam NTACL for teachers
The code was broken which resulted in an ever growing list of acl for
files in teacher home directories and in the worst case an error
which prevented the teacher from starting an exam.

The code is fixed but we also do not set acl on teachers anymore.

```
Internal server error during "schoolexam/exam/start".
Request: schoolexam/exam/start

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/decorators.py", line 259, in _run
    result = self._function(*args, **kwargs)  # type: Union[BaseException, _T]
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/schoolexam/__init__.py", line 813, in _thread
    self.set_nt_acls_on_exam_folders(my.project.getRecipients())
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/schoolexam/__init__.py", line 289, in set_nt_acls_on_exam_folders
    self.deny_owner_change_permissions(filename=str(os.path.join(root, f)))
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/schoolexam/__init__.py", line 274, in deny_owner_change_permissions
    setntacl(self.lp, filename, new_sddl, owner_sid, system_session_unix())
  File "/usr/lib/python3/dist-packages/samba/ntacls.py", line 227, in setntacl
    ndr_pack(ntacl))
OSError: [Errno 28] No space left on device: '/home/school1/lehrer/t1/windows-profiles/default.V6/NTUSER.DAT'
```

I also deleted the `init_windows_profiles` method, because it didn't
work. The method just returned because it could not read
`sambaNTPassword`.
`ucs-school-umc-distribution/umc/python/distribution/util.py::_create_project_dir`
is already creating the home directory.

Issue univention/ucsschool#1300