Bug #53841: open summary in text mode instead of byte mode
This fixes:
```
2021-10-14 21:56:49 ERROR ucs_test_school.__exit__:195  *** Cleanup after exception: <class '_csv.Error'> Error('iterator should return strings, not bytes (did you open the file in text mode?)')
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/importusers_cli_v2.py", line 315, in run
    self.test()
  File "255_import-users_summary_ok_in_dry_run.py", line 71, in test
    for index, row in enumerate(reader):
  File "/usr/lib/python3.7/csv.py", line 111, in __next__
    self.fieldnames
  File "/usr/lib/python3.7/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)
```