Bug #52607: ignore __pycache__ directory to be present in hooks directory
Traceback (most recent call last):
  File "82_legacy_hooks.py", line 546, in <module>
    cli_tester.check_for_non_empty_pyhooks()
  File "/usr/lib/python2.7/dist-packages/univention/testing/ucsschool/importusers_cli_v2.py", line 522, in check_for_non_empty_pyhooks
    raise ImportException(msg)
univention.testing.ucsschool.importusers_cli_v2.ImportException: The directory '/usr/share/ucs-school-import/pyhooks' seems to be non-empty: ['__pycache__'] That often causes problems for tests. Please remove all files in it.