Bug #52607: [ucs-test-ucsschool]: migrate tests to pytest and make them Python 3 compatible
Bug #52607: migrate get_s4_rejected() to Python 3

Traceback (most recent call last):
  File "03_computerroom_endExam", line 47, in test_umc
    existing_rejects = get_s4_rejected()
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/exam.py", line 48, in get_s4_rejected
    found = re.findall(r"DN:\s\w{2,4}=.*", out)
  File "/usr/lib/python3.7/re.py", line 223, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object

Bug #52607: migrate remove_samba_warnings() to Python 3

Traceback (most recent call last):
  File "96_samba4_sid_allocation.py", line 302, in <module>
    exit(TestSambaSIDAllocation.main())
  File "96_samba4_sid_allocation.py", line 206, in main
    initial_next_rid = self.s4_search("(objectClass=rIDSet)", "rIDNextRID")
  File "96_samba4_sid_allocation.py", line 81, in s4_search
    stdout, stderr = self.create_and_run_process(cmd)
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/test_samba4.py", line 61, in create_and_run_process
    stdout = self.remove_samba_warnings(stdout)
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/test_samba4.py", line 44, in remove_samba_warnings
    input_str = input_str.replace("WARNING: No path in service IPC$ - making it unavailable!", "")
TypeError: a bytes-like object is required, not 'str'

Bug #52607: migrate remove_dcs_from_global_groups() to Python 3

Traceback (most recent call last):
  File "30_import-create_ou_alter_dhcpd_base.py", line 14, in <module>
    eio.import_ou_alter_dhcpd_base_flag(use_cli_api=True, use_python_api=False)
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/importou.py", line 1065, in import_ou_alter_dhcpd_base_flag
    remove_ou(ou_name)
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/importou.py", line 97, in remove_ou
    schoolenv.cleanup_ou(ou_name)
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/ucs_test_school.py", line 392, in cleanup_ou
    self.remove_dcs_from_global_groups(ou_name)
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/ucs_test_school.py", line 428, in remove_dcs_from_global_groups
    for dn in unique_member_attr
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/ucs_test_school.py", line 429, in <listcomp>
    if dn.endswith(",ou={},{}".format(ou_name, self.ldap_base))
TypeError: endswith first arg must be bytes or a tuple of bytes, not str

Bug #52607: ucs-test-ucsschool: fix group handling

Traceback (most recent call last):
  File "75_ldap_acls_admins.py", line 124, in <module>
    main()
  File "75_ldap_acls_admins.py", line 26, in main
    school, is_staff=False, is_teacher=True
  File "/usr/lib/python2.7/dist-packages/univention/testing/ucsschool/ucs_test_school.py", line 999, in create_school_admin
    user_udm.modify()
  File "/usr/lib/python2.7/dist-packages/univention/admin/handlers/users/user.py", line 1420, in modify
    return super(object, self).modify(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/univention/admin/handlers/__init__.py", line 636, in modify
    dn = self._modify(modify_childs, ignore_license=ignore_license, response=response)
  File "/usr/lib/python2.7/dist-packages/univention/admin/handlers/__init__.py", line 1333, in _modify
    self._ldap_post_modify()
  File "/usr/lib/python2.7/dist-packages/univention/admin/handlers/users/user.py", line 1660, in _ldap_post_modify
    self.__update_groups()
  File "/usr/lib/python2.7/dist-packages/univention/admin/handlers/users/user.py", line 1532, in __update_groups
    if group and not case_insensitive_in_list(group, old_groups):
  File "/usr/lib/python2.7/dist-packages/univention/admin/handlers/users/user.py", line 832, in case_insensitive_in_list
    assert isinstance(dn, six.text_type)
AssertionError

Bug #52607: fix 90_ucsschool/96_samba4_sid_allocation.py

The SID in the LDAP and Samba4 for the test user 'ucs_school_test_user_nrg1ch7g' are different: 'b'S-1-5-21-1082416352-863439154-2938737740-7124'' vs. 'S-1-5-21-1082416352-863439154-2938737740-7124' in Samba4 LDB.