test: Skip tests in large school env
Temporary skip of the following tests:

```
90_ucsschool.303_http-api_auth_test.primary300.test_http_api_auth_test (This one is flaky)

Traceback (most recent call last):
  File "/usr/share/ucs-test/90_ucsschool/303_http-api_auth_test.py", line 36, in test_http_api_auth_test
    ssl_verify=True,
  File "/usr/lib/python3/dist-packages/ucsschool/http_api/client.py", line 386, in __init__
    setattr(self, cls_name, kls(self))
  File "/usr/lib/python3/dist-packages/ucsschool/http_api/client.py", line 508, in __init__
    self.resource_url = self.client.resource_urls[self.resource_name]
  File "/usr/lib/python3/dist-packages/ucsschool/http_api/client.py", line 402, in resource_urls
    self._resource_urls = self.call_api("get", ".")
  File "/usr/lib/python3/dist-packages/ucsschool/http_api/client.py", line 499, in call_api
    raise exc(msg, status_code=response.status_code)
ucsschool.http_api.client.PermissionError: Received status_code=403 with reason='Forbidden' for requests.get(**url='https://primary300.autotest300.test/api/v1/', data=None, files={}, params=None, auth=('zljfb11con', '***********'), headers={'Accept': 'application/json'}).

```

```
90_ucsschool.70_users_module.primary300.test_users_module (This one always fails)

Traceback (most recent call last):
  File "/usr/share/ucs-test/90_ucsschool/70_users_module.py", line 121, in test_users_module
    _test(student_classes, teacher_classes, [ou], ucr, ou, connection=umc_connection)
  File "/usr/share/ucs-test/90_ucsschool/70_users_module.py", line 91, in _test
    user.verify()
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/importusers.py", line 383, in verify
    self.dn, expected_attr=self.expected_attributes(), strict=True, should_exist=True
  File "/usr/lib/python3/dist-packages/univention/testing/utils.py", line 226, in verify_ldap_object
    delay)
  File "/usr/lib/python3/dist-packages/univention/testing/utils.py", line 177, in retry_on_error
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/lib/python3/dist-packages/univention/testing/utils.py", line 167, in retry_on_error
    return func()
  File "/usr/lib/python3/dist-packages/univention/testing/utils.py", line 293, in __verify_ldap_object
    raise LDAPObjectValueMissing(msg)
univention.testing.utils.LDAPObjectValueMissing: DN: uid=sp69vtsbei,cn=mitarbeiter,cn=users,ou=testou1764,dc=autotest300,dc=test
givenName: [b'hpp0pik4ln'], missing: 'first_name2'; unexpected: 'hpp0pik4ln'
mailPrimaryAddress: [b'sp69vtsbei@demoschool.example.com'], missing: 'c3fuhc2o7h@demoschool.example.com'; unexpected: 'sp69vtsbei@demoschool.example.com'
sn: [b'zdhaeid3ru'], missing: 'last_name2'; unexpected: 'zdhaeid3ru'
```

```
90_ucsschool.104_delete_computers_delete_related_objects.replica300-s1.test_FLAKY_delete_computers_delete_related_objects (flaky)

Traceback (most recent call last):
  File "/usr/share/ucs-test/90_ucsschool/104_delete_computers_delete_related_objects.py", line 89, in test_FLAKY_delete_computers_delete_related_objects
    check_ldap(school, computers, should_exist=False)
  File "/usr/share/ucs-test/90_ucsschool/104_delete_computers_delete_related_objects.py", line 43, in check_ldap
    assert not found, "Object unexpectedly found:(%r)" % found
AssertionError: Object unexpectedly found:([('relativeDomainName=jmum2heifg,zoneName=autotest300.test,cn=dns,dc=autotest300,dc=test', {'zoneName': [b'autotest300.test'], 'relativeDomainName': [b'jmum2heifg'], 'dNSTTL': [b'10800'], 'aRecord': [b'11.112.73.117'], 'objectClass': [b'univentionObject', b'top', b'dNSZone'], 'univentionObjectType': [b'dns/host_record']})])
assert not [('relativeDomainName=jmum2heifg,zoneName=autotest300.test,cn=dns,dc=autotest300,dc=test', {'aRecord': [b'11.112.73.11...L': [b'10800'], 'objectClass': [b'univentionObject', b'top', b'dNSZone'], 'relativeDomainName': [b'jmum2heifg'], ...})]
```

Issue univention/ucsschool#1235