Bug #52607: migrate remove_samba_warnings() to Python 3
Traceback (most recent call last):
  File "96_samba4_sid_allocation.py", line 302, in <module>
    exit(TestSambaSIDAllocation.main())
  File "96_samba4_sid_allocation.py", line 206, in main
    initial_next_rid = self.s4_search("(objectClass=rIDSet)", "rIDNextRID")
  File "96_samba4_sid_allocation.py", line 81, in s4_search
    stdout, stderr = self.create_and_run_process(cmd)
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/test_samba4.py", line 61, in create_and_run_process
    stdout = self.remove_samba_warnings(stdout)
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/test_samba4.py", line 44, in remove_samba_warnings
    input_str = input_str.replace("WARNING: No path in service IPC$ - making it unavailable!", "")
TypeError: a bytes-like object is required, not 'str'