Bug #52633: migrate ucs-school-umc-diagnostic to Python 3
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/__init__.py", line 280, in execute
    result = execute(umc_module, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/plugins/901_ucsschool_import_counter.py", line 77, in run
    prefix = uid.rstrip("0123456789")
TypeError: a bytes-like object is required, not 'str'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/__init__.py", line 280, in execute
    result = execute(umc_module, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/plugins/904_ucsschool_remove_from_school_consistenceny.py", line 80, in run
    roles = {role.split(":")[-1] for role in ucsschool_roles if ":school:" in role}
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/plugins/904_ucsschool_remove_from_school_consistenceny.py", line 80, in
    roles = {role.split(":")[-1] for role in ucsschool_roles if ":school:" in role}
TypeError: a bytes-like object is required, not 'str'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/__init__.py", line 280, in execute
    result = execute(umc_module, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/plugins/905_ucsschool_check_backend.py", line 80, in run
    installed, version = stdout.split(",")
TypeError: a bytes-like object is required, not 'str'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/__init__.py", line 280, in execute
    result = execute(umc_module, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/plugins/908_ucsschool_school_admin_accounts.py", line 99, in run
    if role_school_admin in role:
TypeError: a bytes-like object is required, not 'str'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/__init__.py", line 280, in execute
    result = execute(umc_module, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/plugins/911_ucsschool_consistency.py", line 64, in run
    res = check_all()  # type: Dict[str, Dict[str, List[str]]]
  File "/usr/lib/python3/dist-packages/ucsschool/lib/consistency.py", line 537, in check_all
    user_issues = user_check.check_user(dn, attrs)
  File "/usr/lib/python3/dist-packages/ucsschool/lib/consistency.py", line 238, in check_user
    if user_obj.is_student(self.lo):
  File "/usr/lib/python3/dist-packages/ucsschool/lib/models/user.py", line 166, in is_student
    return self.__check_object_class(lo, b"ucsschoolStudent", self._legacy_is_student)
  File "/usr/lib/python3/dist-packages/ucsschool/lib/models/user.py", line 217, in __check_object_class
    return object_class.encode("UTF-8") in obj.oldattr.get("objectClass", [])
AttributeError: 'bytes' object has no attribute 'encode'

conform to API change in appcenter:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/__init__.py", line 280, in execute
    result = execute(umc_module, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/plugins/910_ucsschool_veyon_app_installed.py", line 122, in install_veyon_proxy_app
    pwdfile=pw_file.name,
  File "/usr/lib/python3/dist-packages/univention/appcenter/actions/__init__.py", line 175, in call
    return obj.call_with_namespace(namespace)
  File "/usr/lib/python3/dist-packages/univention/appcenter/actions/__init__.py", line 181, in call_with_namespace
    result = self.main(namespace)
  File "/usr/lib/python3/dist-packages/univention/appcenter/actions/install.py", line 69, in main
    for app in apps:
TypeError: 'App' object is not iterable