Bug #52608: [ucs-school-umc-exam] migrate to Python 3
Fix error handling when starting and stopping exams:
* Revert git:cc1a2118dd55e315489160b13d4db4983723be58 Bug #51166.
  → It let the UMC module process crash and the progress bar hangs forever.
  A thread finish callback must never raise an exception.
* The new behavior aborts the progress bar correctly, so that the error
  message is shown in the eror page of the exam mode.
* Additionally a traceback dialog pops up.
* Additionally the traceback is logged into
  /var/log/univention/management-console-web-server.log.

Adjust to API change in python-samba

Fix error handling:
Traceback (most recent call last):
  File "/usr/sbin/univention-management-console-module", line 122, in <module>
    notifier.loop()
  File "/usr/lib/python3/dist-packages/notifier/nf_generic.py", line 306, in loop
    step()
  File "/usr/lib/python3/dist-packages/notifier/nf_generic.py", line 297, in step
    __min_timer = dispatch.dispatcher_run()
  File "/usr/lib/python3/dist-packages/notifier/dispatch.py", line 75, in dispatcher_run
    if not disp():
  File "/usr/lib/python3/dist-packages/notifier/threads.py", line 161, in _simple_threads_dispatcher
    task.announce()
  File "/usr/lib/python3/dist-packages/notifier/threads.py", line 139, in announce
    self._callback(self, self._result)
  File "/usr/lib/python3/dist-packages/notifier/__init__.py", line 105, in __call__
    return self._function(*tmp, **self._kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/schoolexam/__init__.py", line 821, in _finished
    self.thread_finished_callback(thread, response, request)
UnboundLocalError: local variable 'response' referenced before assignment

Fix broken "default" in UCR variable description, as this is now evaluated.