Bug #52640: [ucs-school-lib] migrate to Python 3
* migrate ipaddr to ipaddress
* fix logging API change

Traceback (most recent call last):
  File "/usr/share/ucs-test/90_ucsschool/401_ucsschool_lib_logger_removes_password.py", line 47, in test_get_file_handler_translates_string_loglevels
    assert get_file_handler(level_name, file_name).level == level_value
  File "/usr/lib/python3/dist-packages/ucsschool/lib/models/utils.py", line 493, in get_file_handler
    fmt = fmt or FILE_LOG_FORMATS[loglevel_int2str(nearest_known_loglevel(level))]
  File "/usr/lib/python3/dist-packages/ucsschool/lib/models/utils.py", line 427, in nearest_known_loglevel
    int_level = logging._levelNames.get(level, 10)
AttributeError: module 'logging' has no attribute '_levelNames'

* fix python 2 output of models list

python -m "ucsschool.lib.models" list "$ROLE" --name=... --school=... printed u"" prefixed strings.
python3 -m "ucsschool.lib.models" list "$ROLE" --name=... --school=... printed b"" prefixed strings.

This causes the test case 404_ucsschool_lib_models_main.py::test_list to fail.

Another error was:
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/ucsschool/lib/models/__main__.py", line 543, in <module>
    cli(obj={})
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/ucsschool/lib/models/__main__.py", line 522, in list_objs
    get_and_print(lo, model_cls, school=school, base="", filter_str=complete_filter)
  File "/usr/lib/python3/dist-packages/ucsschool/lib/models/__main__.py", line 480, in get_and_print
    get_and_print_with_school(lo, model_cls, school, filter_str)
  File "/usr/lib/python3/dist-packages/ucsschool/lib/models/__main__.py", line 439, in get_and_print_with_school
    objs = model_cls.get_all(lo, school=school, filter_str=filter_str)
  File "/usr/lib/python3/dist-packages/ucsschool/lib/models/base.py", line 991, in get_all
    for udm_obj in cls.lookup(lo, school, complete_filter, superordinate=superordinate):
  File "/usr/lib/python3/dist-packages/ucsschool/lib/models/user.py", line 650, in lookup
    "&", [parse(cls.type_filter), parse(filter_format("ucsschoolSchool=%s", [school]))]
  File "/usr/lib/python3/dist-packages/ldap/filter.py", line 57, in filter_format
    return filter_template % tuple(escape_filter_chars(v) for v in assertion_values)
  File "/usr/lib/python3/dist-packages/ldap/filter.py", line 57, in <genexpr>
    return filter_template % tuple(escape_filter_chars(v) for v in assertion_values)
  File "/usr/lib/python3/dist-packages/ldap/filter.py", line 41, in escape_filter_chars
    s = assertion_value.replace('\\', r'\5c')
TypeError: a bytes-like object is required, not 'str'