Bug #54039: Fix missing "Marktplatz" share
Due to bug #54039 the "Marktplatz" share was missing
(01_test_school_creation_marktplatz_share.py had triggered the bug
resulting in a missing share).
The test now creates a new share for new test school.

Traceback (most recent call last):
  File "/usr/share/ucs-test/90_ucsschool/22_computerroom_module_settings.py", line 37, in test_computerroom_module_settings
    room.test_settings(school, teacher, teacher_dn, created_computers[1].ip[0], ucr, client)
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/computerroom.py", line 597, in test_settings
    ucr,
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/computerroom.py", line 643, in check_behavior
    self.check_share_behavior(user, ip_address, shareMode)
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/computerroom.py", line 307, in check_share_behavior
    self.check_share_access(user, ip_address, 0, 0)
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/computerroom.py", line 302, in check_share_access
    self.check_marktplatz_read(user, ip_address, expected_result=expected_marktplatz_result)
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/computerroom.py", line 291, in check_marktplatz_read
    user, ip_address, share="Marktplatz", passwd=passwd, expected_result=expected_result
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/computerroom.py", line 56, in decorated
    lambda: func(*args, **kwargs), exceptions=(CmdCheckFail), retry_count=8, delay=4
  File "/usr/lib/python3/dist-packages/univention/testing/utils.py", line 166, in retry_on_error
    return func()
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/computerroom.py", line 56, in <lambda>
    lambda: func(*args, **kwargs), exceptions=(CmdCheckFail), retry_count=8, delay=4
  File "/usr/lib/python3/dist-packages/univention/testing/ucsschool/computerroom.py", line 1020, in check_share_read
    expected_result,
AssertionError: Read share ('Marktplatz') result (1), expected (0)